package id.ac.poliban.mi.sultan.listviewpahlawan;

import java.util.ArrayList;
import java.util.List;

public class HeroData {
    static List<Hero> getAllHero(){
        List<Hero> data = new ArrayList<>();
        {
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sudirman.jpg/486px-Sudirman.jpg", "Soedirman", "Jenderal Besar Raden Soedirman (EYD: Sudirman; lahir 24 Januari 1916 – meninggal 29 Januari 1950 pada umur 34 tahun[a]) adalah seorang perwira tinggi Indonesia pada masa Revolusi Nasional Indonesia. Sebagai panglima besar Tentara Nasional Indonesia pertama, ia adalah sosok yang dihormati di Indonesia. Terlahir dari pasangan rakyat biasa di Purbalingga, Hindia Belanda, Soedirman diadopsi oleh pamannya yang seorang priyayi. Setelah keluarganya pindah ke Cilacap pada tahun 1916, Soedirman tumbuh menjadi seorang siswa rajin; ia sangat aktif dalam kegiatan ekstrakurikuler, termasuk mengikuti program kepanduan yang dijalankan oleh organisasi Islam Muhammadiyah. Saat di sekolah menengah, Soedirman mulai menunjukkan kemampuannya dalam memimpin dan berorganisasi, dan dihormati oleh masyarakat karena ketaatannya pada Islam. Setelah berhenti kuliah keguruan, pada 1936 ia mulai bekerja sebagai seorang guru, dan kemudian menjadi kepala sekolah, di sekolah dasar Muhammadiyah; ia juga aktif dalam kegiatan Muhammadiyah lainnya dan menjadi pemimpin Kelompok Pemuda Muhammadiyah pada tahun 1937. Setelah Jepang menduduki Hindia Belanda pada 1942, Soedirman tetap mengajar. Pada tahun 1944, ia bergabung dengan tentara Pembela Tanah Air (PETA) yang disponsori Jepang, menjabat sebagai komandan batalion di Banyumas. Selama menjabat, Soedirman bersama rekannya sesama prajurit melakukan pemberontakan, namun kemudian diasingkan ke Bogor."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Hasyim_Asyari.jpg/220px-Hasyim_Asyari.jpg", "Hasyim Asy'ari", "Kiai Haji Mohammad Hasjim Asy'arie bagian belakangnya juga sering dieja Asy'ari atau Ashari (lahir di Kabupaten Jombang, Jawa Timur, 14 Februari 1871 – meninggal di Jombang, Jawa Timur, 21 Juli 1947 pada umur 76 tahun; 24 Dzul Qo'dah 1287 H- 3 Ramadhan 1366 H; dimakamkan di Tebu Ireng, Jombang) adalah salah seorang Pahlawan Nasional Indonesia[2] yang merupakan pendiri Nahdlatul Ulama, organisasi massa Islam yang terbesar di Indonesia. Di kalangan Nahdliyin dan ulama pesantren ia dijuluki dengan sebutan Hadratus Syeikh yang berarti maha guru."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Diponegoro.jpg/220px-Diponegoro.jpg", "Pangeran Diponegoro", "Bendara Pangeran Harya Dipanegara (lebih dikenal dengan nama Diponegoro, lahir di Ngayogyakarta Hadiningrat, 11 November 1785 – meninggal di Makassar, Hindia Belanda, 8 Januari 1855 pada umur 69 tahun) adalah salah seorang pahlawan nasional Republik Indonesia. Pangeran Diponegoro terkenal karena memimpin Perang Diponegoro/Perang Jawa (1825-1830) melawan pemerintah Hindia Belanda. Perang tersebut tercatat sebagai perang dengan korban paling besar dalam sejarah Indonesia."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg/220px-Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg", "Ki Hadjar Dewantara", "Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 – meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun;[1] selanjutnya disingkat sebagai \"Soewardi\" atau \"KHD\") adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Bung_Tomo.jpg/220px-Bung_Tomo.jpg", "Sutomo", "Sutomo (lahir di Surabaya, Jawa Timur, 3 Oktober 1920 – meninggal di Padang Arafah, Arab Saudi, 7 Oktober 1981 pada umur 61 tahun)[1] lebih dikenal dengan sapaan akrab oleh rakyat sebagai Bung Tomo, adalah pahlawan yang terkenal karena peranannya dalam membangkitkan semangat rakyat untuk melawan kembalinya penjajah Belanda melalui tentara NICA, yang berakhir dengan pertempuran 10 November 1945 yang hingga kini diperingati sebagai Hari Pahlawan."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Portret_van_Tuanku_Imam_Bonjol.jpg/220px-Portret_van_Tuanku_Imam_Bonjol.jpg", "Tuanku Imam Bonjol", "Tuanku Imam Bonjol (lahir di Bonjol, Pasaman, Sumatra Barat, Indonesia, 1772 - wafat dalam pengasingan dan dimakamkan di Lotta, Pineleng, Minahasa, 6 November 1864) adalah salah seorang ulama, pemimpin dan pejuang yang berperang melawan Belanda dalam peperangan yang dikenal dengan nama Perang Padri pada tahun 1803-1838.[1] Tuanku Imam Bonjol diangkat sebagai Pahlawan Nasional Indonesia berdasarkan SK Presiden RI Nomor 087/TK/Tahun 1973, tanggal 6 November 1973."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg/200px-COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg", "Kartini", "Raden Adjeng Kartini (lahir di Jepara, Hindia Belanda, 21 April 1879 – meninggal di Rembang, Hindia Belanda, 17 September 1904 pada umur 25 tahun) atau sebenarnya lebih tepat disebut Raden Ayu Kartini[1] adalah seorang tokoh Jawa dan Pahlawan Nasional Indonesia. Kartini dikenal sebagai pelopor kebangkitan perempuan pribumi."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/id/1/17/Pattimura_2.jpg", "Pattimura", "Pattimura (Thomas Matulessy) lahir di Haria, pulau Saparua, Maluku, 8 Juni 1783 – meninggal di Ambon, Maluku, 16 Desember 1817 pada umur 34 tahun), juga dikenal dengan nama Kapitan Pattimura adalah Pahlawan nasional Indonesia dari Maluku.\n" +
                    "\n" +
                    "Menurut buku biografi Pattimura versi pemerintah yang pertama kali terbit, M Sapija menulis, \"Bahwa pahlawan Pattimura tergolong turunan bangsawan dan berasal dari Nusa Ina (Seram)\". Ayahnya yang bernama Antoni Matulessy adalah anak dari Kasimiliali Pattimura Mattulessy. Yang terakhir ini adalah putra raja Sahulau. Sahulau merupakan nama orang di negeri yang terletak dalam sebuah teluk di Seram."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Mahmud_Badaruddin_II.jpg/220px-Mahmud_Badaruddin_II.jpg", "Sultan Mahmud Badaruddin II", "Sultan Mahmud Badaruddin II (l: Palembang, 1767, w: Ternate, 26 September 1852)[1] adalah pemimpin kesultanan Palembang-Darussalam selama dua periode (1803-1813, 1818-1821), setelah masa pemerintahan ayahnya, Sultan Muhammad Bahauddin (1776-1803). Nama aslinya sebelum menjadi Sultan adalah Raden Hasan Pangeran Ratu."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/id/thumb/5/5a/Cut_Nyak_Meutia.jpg/220px-Cut_Nyak_Meutia.jpg", "Cut Nyak Meutia", "Tjoet Nyak Meutia (lahir di Keureutoe, Pirak, Aceh Utara, 15 Februari 1870 – meninggal di Alue Kurieng, Aceh, 24 Oktober 1910 pada umur 40 tahun) adalah pahlawan nasional Indonesia dari daerah Aceh. Ia dimakamkan di Alue Kurieng, Aceh. Ia menjadi pahlawan nasional Indonesia berdasarkan Surat Keputusan Presiden Nomor 107/1964 pada tahun 1964."));
        }
        return data;
    }
}
